.envrc
devenv.lock
devenv.nix
example/devenv.nix

Blackfire is incompatible with PHP < 8, so let's remove it for now from the standard configuration 🙂
Also, use the environment to fix PHP version customization, which was not working correctly before.

[noticket] Use environment for PHP version to allow customization in downstream configurations.

---

devenv.nix

Setting `services.mailhog.uiListenAddress` is already set to `"127.0.0.1:8025"` by default:   https://devenv.sh/reference/options/#servicesmailhoguilistenaddress

Remove redeclaration of default setting

---

README.md

Turned out, I haven't seen, that there is a command to import the list of links.
This PR will highlight the existence of the command a little bit.

Make importdb more visible in the README.md

---

examples/sw6/devenv.nix

We should not show example of default values.

adjust example config to enable additional services

---

.github/workflows/publish_docs_to_wiki.yml

Changes to the pipeline for publishing docs to wiki are not triggering it.
Add file to paths that are checked.

fix: Add changes of publish_docs_to_wiki.yml as trigger for pipeline

---

devenv.nix
docs/Options.md

mysqld configurations can already added via a one liner: 
```
{
services.mysql.settings.mysqld.config=value;
}
```
No additional config is required.
Removes a config option provided by #23 
///

Remove obsolete config for mysqld

---

devenv.nix

See #32 
Skips further execution of the entry script if `mysqladmin` is missing
See #32 
#32

[noticket] Add skip if mysqladmin is missing

---

devenv.nix

REDIS_DSN is not set if Redis is enabled.
It adds REDIS_DSN to the env vars, if Redis is enabled.
Any devenv setup importing this with redis enabled, does not have REDIS_DSN set.
None.

Add REDIS_DSN to env vars if enabled

---

devenv.nix

https://github.com/cachix/devenv/commit/4e5a2d53335c5858200715a7c56e648ee6ceb551
devenv changed the default, which broke my database for one project unattended.
Set mysql80 as default

[NOTICKET] set mysql 8.0 as default database

---

devenv.nix
docs/Options.md

If devenv is placed in the parent folder of the project - whyever - this will result in an exit instead of keeping the project running
Switch an `exit` with a `sleep`
Setup a new project, run and setup it initially and restart devenv
///

[noticket] Add fix for devenv usage outside of project folder

---

devenv.nix

We don't need that cache in development environments, while it throws `Warning: fileperms(): stat failed for /var/www/html/var/cache/*/Shopware_Core_KernelProdDebugContainer.php` after clearing cache-

fix: [NOTICKET] remove opcache.enable_file_override

---

devenv.nix

The `cc` command is not working. It instantly terminates.
A missing directory separator (`/`) is added to the path to `bin/console`.
Start a Shopware 6 environment, execute `cc` and you will see no output.
No issue.

fix: Add missing directory separator in cc script

---

devenv.nix
docs/Options.md

Before, it was not possible to configure the MySQL bin logs for this setup without using devenv-native configuration.
Adds an option to enable/disable the MySQL bin logs.

MySQL Binary Log: Add option to enable/disable

---

devenv.nix
docs/Options.md

It adds an alternative to Elasticsearch to the setup: OpenSearch
It adds a OpenSearch-enabling config setting and the following configuration of the devenv setup. It reuses the Elasticsearch config settings.
-
-

OpenSearch: Add configuration

---

.envrc
.github/workflows/test_examples.yml
README.md
docs/Update.md
examples/sw5/.envrc
examples/sw5/devenv.yaml
examples/sw6/.envrc
examples/sw6/devenv.yaml

- Adjust used envrc version to 0.6.2
- Change remote ref usage
* dotenv produces an error if used with devenv `v0.6.2`
* combination of `url: git+https` with `?ref=v1.0.0` doesn't work
* Increase version to `1.0.1`
* Increase required devenv version to `v0.6.3`
* Increase version of `devenv-shopware` to `1.0.1`
* Change remote ref example

chore: [noticket] Misc changes regarding release

---

.github/workflows/test_examples.yml
devenv.nix
examples/sw5/devenv.yaml
examples/sw6/devenv.yaml

Devenv sometimes installs NPM in version 10.X. This version is not supported by sw, due which some commands will fail
Adds a hotfix via env variable to the boot
///
///

Add NPM_CONFIG_ENGINE_STRICT for new npm10

---

modules/php.nix

The config is `opcache.enable`: https://www.php.net/manual/de/opcache.configuration.php#ini.opcache.enable

fix: correct phpConfig for enabled opcache

---

devenv.nix
docs/Home.md
modules/mysql.nix

Shopware recommends mysql settings here https://developer.shopware.com/docs/guides/hosting/performance/performance-tweaks.html#mysql-configuration 
So we want to have recommendations as default.
Changes the default values from `group_concat_max_len` to `32000` and `sql_mode` to mysql standard, but without `ONLY_FULL_GROUP_BY`.
Also i've added the env variable `SQL_SET_DEFAULT_SESSION_VARIABLES` with the value `0` as default for the setup.

feat: [noticket] set default mysql config values as recommended by shopware

---

.github/workflows/publish_docs_to_wiki.yml

We want the wiki to be compatible with the latest release
Removes the publishing of wikis for every push to main
///
///

Change wiki publish to tag releases

---

devenv.nix

Since Shopware 6.5 the environment variable to configure the Opensearch URL is no longer called `SHOPWARE_ES_HOSTS` but is now `OPENSEARCH_URL`.
It also sets the env variable `OPENSEARCH_URL` according to the option `cfg.elasticsearchPort` so switching the default port would also work with Shopware 6.5
https://developer.shopware.com/docs/guides/hosting/infrastructure/elasticsearch/elasticsearch-setup.html#variables-in-your-env

Add OPENSEARCH_URL

---

README.md

The only place where the default values are currently visible is in the `devenv.nix` file
Adjusts the README.md
Look for the default values
/

Add default values for MySQL to README.md

---

modules/caddy.nix
modules/php.nix
modules/scripts.nix

These changes ensure compatibility with devenv 1.x
I disabled automatic ca installation for caddy as this prevented the server from starting up when using tls. Furthermore I removed the usage of `currentSystem` because it was removed in devenv version 1.0
Fixes #94

Devenv 1.x
